services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user
    container_name: user-service
    depends_on:
      - rabbitmq
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8081:8081'

  email-service:
    build: ./email
    container_name: email-service
    depends_on:
      - rabbitmq
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - '8082:8082'

volumes:
  postgres_data:
